# Generated by Django 5.2.7 on 2025-10-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wants_to_be_admin',
            field=models.BooleanField(default=False),
        ),
    ]
